name: Terraform Common
description: Run terraform plan or apply

inputs:
  action:
    required: true
  env_name:
    required: true

runs:
  using: "composite"
  steps:

    - name: Set working directory
      working-directory: ${{ github.workspace }}/${{ inputs.env_name }}
      run: echo "WORKSPACE=${GITHUB_WORKSPACE}" 
      shell: bash

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: "arn:aws:iam::424851482428:role/abc"
        aws-region: us-east-1

    - name: change directory
      run: cd ${{ inputs.env_name }}
      shell: bash


    - name: Terraform Init
      working-directory: ${{ github.workspace }}/${{ inputs.env_name }}
      run:  
          |
          
          cd ${{ github.workspace }}/${{ inputs.env_name }}
          pwd
          ls -la
          terraform init
      shell: bash

    -  name: Terraform Validate
       working-directory: ${{ github.workspace }}/${{ inputs.env_name }}
       shell: bash
       run:  
          | 
          pwd 
          terraform validate


    - name: Run Terraform
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.env_name }}
      run: |
        if [[ "${{ inputs.action }}" == "plan" ]]; then
          echo "terraform plan"
          terraform plan
        elif [[ "${{ inputs.action }}" == "apply" ]]; then
          terraform apply 
        fi
