name: Terraform Common
description: Run terraform plan or apply

inputs:
  action:
    required: true
  env_name:
    required: true
  tf_var_file:
    required: false

runs:
  using: "composite"
  steps:

    - name: Set working directory
      working-directory: ${{ github.workspace }}
      run: echo "WORKSPACE=${GITHUB_WORKSPACE}" 
      shell: bash

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: "arn:aws:iam::424851482428:role/abc"
        aws-region: us-east-1
    
    - name: Terraform Init
      run:  terraform init -var-file="${{ inputs.tf_var_file }}"
      shell: bash

    -  name: Terraform Validate
       shell: bash
       run:  terraform validate

    -  name: Terraform Format
       shell: bash
       run:  terraform fmt

    - name: Run Terraform
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        if [[ "${{ inputs.action }}" == "plan" ]]; then
          echo "terraform plan -var-file="${{ inputs.tf_var_file }}" -out=tfplan"
          terraform plan -var-file="${{ inputs.tf_var_file }}" -out=tfplan
        elif [[ "${{ inputs.action }}" == "apply" ]]; then
          terraform apply "tfplan"
        fi
